{{- if .Values.storage.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvc.name }}
spec:
  accessModes:
    {{- toYaml .Values.storage.pvc.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
{{- end }}
